### ISSUE TITLE
Check if a node has seccomp support. 

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/seccomp-operator#76]
We could verify if a node supports seccomp by:

```go
func IsEnabled() bool {
	// Check if Seccomp is supported, via CONFIG_SECCOMP.
	if err := unix.Prctl(unix.PR_GET_SECCOMP, 0, 0, 0, 0); err != unix.EINVAL {
		// Make sure the kernel has CONFIG_SECCOMP_FILTER.
		if err := unix.Prctl(unix.PR_SET_SECCOMP, unix.SECCOMP_MODE_FILTER, 0, 0, 0); err != unix.EINVAL {
			return true
		}
	}
	return false
}
```

The question is, what would we do in the case that this function returns `false`? We could make the reconciliation a noop, throw a warning event. Right now this would not bring much benefit to the user. How could we prevent that a workload with a profile gets scheduled on a node which is not supporting seccomp?

**Comment by hasheddan** [comment]
> How could we prevent that a workload with a profile gets scheduled on a node which is not supporting seccomp?

Seems like a good use-case for an admission webhook.

**Comment by saschagrunert** [comment]
> > How could we prevent that a workload with a profile gets scheduled on a node which is not supporting seccomp?
> 
> Seems like a good use-case for an admission webhook.

Yeah, so probably a good topic for post v1.

**Comment by pjbgf** [comment]
I think if it returns `false` we could tag the node with something meaningful, which could then be used with [node selectors](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-nginx.yaml).
If we have the capacity, we potentially could do now:

1. Implement the validation and tagging.
2. Document so users can already benefit from being able to not schedule pods that must run with seccomp.

And then once the admission webhook is done:

3. Mutate pods to automatically have the node selector based on some configuration or tag/annotation (TBC).

Or we could just do three of them post v1.

**Comment by saschagrunert** [comment]
Sounds good, let's move it to v2 to decrease the complexity.

**Comment by saschagrunert** [comment]
#85 contains a first RFC, but does not necessarily land in v1.

**Comment by hasheddan** [comment]
@saschagrunert do you know how the kubelet handles if a pod is scheduled to it with a seccomp profile and seccomp is not enabled? I would imagine it likely behaves similar to if the profile does not exist?

**Comment by saschagrunert** [comment]
> @saschagrunert do you know how the kubelet handles if a pod is scheduled to it with a seccomp profile and seccomp is not enabled? I would imagine it likely behaves similar to if the profile does not exist?

In CRI-O we fail scheduling if the profile is not set to unconfined:
https://github.com/cri-o/cri-o/blob/98ea748e2551f01919cfc33eb9f0f9403888f1a6/server/container_create.go#L614

But it depends if the builds of CRI-O and runc have seccomp enabled. For example if a node does support seccomp, but runc is build without it then we will still fail to schedule the workload. The other way around if everything is build with seccomp support but the node disables it on boot, then we also fail. It’s tricky, that’s why we could:

- verify that a profile works on a node before writing it to disk
- excluding nodes which do not support seccomp at all

**Comment by saschagrunert** [comment]
This is mainly done, let's defer the mutating webhook discussion to v2.
